var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/reports/page.js")
R.c("server/chunks/ssr/[externals]_node:crypto_2861b06e._.js")
R.c("server/chunks/ssr/Desktop_Inventory_my-app_src_generated_prisma_runtime_client_880022ae.js")
R.c("server/chunks/ssr/3d860_Inventory_my-app_src_generated_prisma_query_compiler_bg_wasm-base64_566b899d.js")
R.c("server/chunks/ssr/Desktop_Inventory_my-app_src_generated_prisma_15912c86._.js")
R.c("server/chunks/ssr/Desktop_Inventory_my-app_src_b20c5d7f._.js")
R.c("server/chunks/ssr/[root-of-the-server]__f711e3e6._.js")
R.c("server/chunks/ssr/65e54_22c3826c._.js")
R.c("server/chunks/ssr/65e54_next_dist_4a57f0b3._.js")
R.c("server/chunks/ssr/65e54_@opentelemetry_api_build_esm_2c8e8e38._.js")
R.c("server/chunks/ssr/65e54_@swc_helpers_cjs__interop_require_wildcard_cjs_8a5bf726._.js")
R.c("server/chunks/ssr/[root-of-the-server]__f0336b73._.js")
R.c("server/chunks/ssr/Desktop_Inventory_my-app_src_app_cc470e6c._.js")
R.c("server/chunks/ssr/65e54_next_dist_client_components_builtin_global-error_72e72b13.js")
R.c("server/chunks/ssr/65e54_next_6fafd3d2._.js")
R.c("server/chunks/ssr/65e54_@stackframe_stack_dist_esm_daa0807f._.js")
R.c("server/chunks/ssr/65e54_@stackframe_stack-shared_dist_esm_8471e67a._.js")
R.c("server/chunks/ssr/65e54_9b9279c9._.js")
R.c("server/chunks/ssr/[root-of-the-server]__96cc3773._.js")
R.c("server/chunks/ssr/Desktop_Inventory_my-app_src_app_loading_tsx_9be55d5b._.js")
R.c("server/chunks/ssr/65e54_next_dist_client_components_80a5828c._.js")
R.c("server/chunks/ssr/65e54_next_dist_client_components_builtin_forbidden_d0681a3e.js")
R.c("server/chunks/ssr/65e54_next_dist_client_components_builtin_unauthorized_a849189d.js")
R.c("server/chunks/ssr/Desktop_Inventory_my-app__next-internal_server_app_reports_page_actions_0d67301e.js")
R.m("[project]/Desktop/Inventory/my-app/node_modules/next/dist/esm/build/templates/app-page.js?page=/reports/page { GLOBAL_ERROR_MODULE => \"[project]/Desktop/Inventory/my-app/node_modules/next/dist/client/components/builtin/global-error.js [app-rsc] (ecmascript, Next.js Server Component)\", METADATA_0 => \"[project]/Desktop/Inventory/my-app/src/app/favicon.ico.mjs { IMAGE => \\\"[project]/Desktop/Inventory/my-app/src/app/favicon.ico (static in ecmascript, tag client)\\\" } [app-rsc] (structured image object, ecmascript, Next.js Server Component)\", MODULE_1 => \"[project]/Desktop/Inventory/my-app/src/app/layout.tsx [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_2 => \"[project]/Desktop/Inventory/my-app/src/app/loading.tsx [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_3 => \"[project]/Desktop/Inventory/my-app/node_modules/next/dist/client/components/builtin/not-found.js [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_4 => \"[project]/Desktop/Inventory/my-app/node_modules/next/dist/client/components/builtin/forbidden.js [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_5 => \"[project]/Desktop/Inventory/my-app/node_modules/next/dist/client/components/builtin/unauthorized.js [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_6 => \"[project]/Desktop/Inventory/my-app/node_modules/next/dist/client/components/builtin/global-error.js [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_7 => \"[project]/Desktop/Inventory/my-app/src/app/reports/page.tsx [app-rsc] (ecmascript, Next.js Server Component)\" } [app-rsc] (ecmascript)")
module.exports=R.m("[project]/Desktop/Inventory/my-app/node_modules/next/dist/esm/build/templates/app-page.js?page=/reports/page { GLOBAL_ERROR_MODULE => \"[project]/Desktop/Inventory/my-app/node_modules/next/dist/client/components/builtin/global-error.js [app-rsc] (ecmascript, Next.js Server Component)\", METADATA_0 => \"[project]/Desktop/Inventory/my-app/src/app/favicon.ico.mjs { IMAGE => \\\"[project]/Desktop/Inventory/my-app/src/app/favicon.ico (static in ecmascript, tag client)\\\" } [app-rsc] (structured image object, ecmascript, Next.js Server Component)\", MODULE_1 => \"[project]/Desktop/Inventory/my-app/src/app/layout.tsx [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_2 => \"[project]/Desktop/Inventory/my-app/src/app/loading.tsx [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_3 => \"[project]/Desktop/Inventory/my-app/node_modules/next/dist/client/components/builtin/not-found.js [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_4 => \"[project]/Desktop/Inventory/my-app/node_modules/next/dist/client/components/builtin/forbidden.js [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_5 => \"[project]/Desktop/Inventory/my-app/node_modules/next/dist/client/components/builtin/unauthorized.js [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_6 => \"[project]/Desktop/Inventory/my-app/node_modules/next/dist/client/components/builtin/global-error.js [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_7 => \"[project]/Desktop/Inventory/my-app/src/app/reports/page.tsx [app-rsc] (ecmascript, Next.js Server Component)\" } [app-rsc] (ecmascript)").exports
